# This file adds the volume mounts for our local development environment:

services:
  backend:
    volumes:
      - ./backend:/app

  frontend:
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
