# This file adds the volume mounts for our local development environment:

services:
  backend:
    volumes:
      - ./backend:/app
    command: npm run start:dev  # Start in watch mode

  frontend:
    volumes:
      - ./frontend/src:/app/src
    command: npm start  # Run the frontend dev server